id: opecha:P006730
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5133
  title: སྟོང་བསྐོར་ཞབས་དྲུང་སྐུ་ཕྲེང་བཅུ་པ་རྗེ་བཙུན་བློ་བཟང་ཐུབ་བསྟན་འཇིགས་མེད་བྱམས་པ་རྒྱ་མཚོ་དཔལ་བཟང་པོའི་རྣམ་ཐར་ལྗོན་པའི་དབང་པོ་
  volume: ''
  author: ''
